/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho1;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Paiva
 */
public class metodoReajuste extends javax.swing.JFrame {

    /**
     * Creates new form metodoReajuste
     */
    public metodoReajuste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancelarReajuste = new javax.swing.JButton();
        btConfirmarReajuste = new javax.swing.JButton();
        campoNCReajuste = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNovaTaxa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 400));
        setSize(new java.awt.Dimension(450, 400));

        btCancelarReajuste.setText("Cancelar");
        btCancelarReajuste.setPreferredSize(new java.awt.Dimension(85, 25));
        btCancelarReajuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarReajusteActionPerformed(evt);
            }
        });

        btConfirmarReajuste.setText("Continuar");
        btConfirmarReajuste.setMaximumSize(new java.awt.Dimension(90, 25));
        btConfirmarReajuste.setPreferredSize(new java.awt.Dimension(85, 25));
        btConfirmarReajuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarReajusteActionPerformed(evt);
            }
        });

        campoNCReajuste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNCReajuste.setToolTipText("Ex: 2");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Nº da Conta Poupança:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reajsute");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Nova Taxa: ");

        campoNovaTaxa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNovaTaxa.setToolTipText("Ex: 15");
        campoNovaTaxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNovaTaxaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btConfirmarReajuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btCancelarReajuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNCReajuste, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(campoNovaTaxa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNCReajuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoNovaTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmarReajuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelarReajuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarReajusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarReajusteActionPerformed
        new Aba4().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btCancelarReajusteActionPerformed

    private void btConfirmarReajusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarReajusteActionPerformed
        int verificar = Integer.parseInt(campoNCReajuste.getText());
       
        if (verificar == Principal.conta2.getNumero()){
            if(campoNovaTaxa.getText()==null || campoNovaTaxa.getText().trim().equals("")){
            }else{
                int i = JOptionPane.showConfirmDialog(null, "Deseja alterar o valor cadastrado para Taxa?", "Confirmação", JOptionPane.YES_NO_OPTION);
                if(i==0){
                    ContaPoupanca.reajuste = Double.parseDouble(campoNovaTaxa.getText());
                }
             }
            int i = JOptionPane.showConfirmDialog(null, "Deseja ralizar o reajuste senhor (a): "+Principal.conta2.getNome(), "Confirmação", JOptionPane.YES_NO_OPTION);
            if(i==0){
                if(ContaPoupanca.reajuste==0){
                    Principal.conta2.reajustar();
                    JOptionPane.showMessageDialog(null, "Reajuste efetuado com Sucesso!");
                }else{
                    Principal.conta2.reajustar(ContaPoupanca.reajuste);
                    JOptionPane.showMessageDialog(null, "Reajuste efetuado com Sucesso!");
                    ContaPoupanca.reajuste = 0;
                }
            }else{
                new Aba4().setVisible(true);
                this.setVisible(false);
             }
                new Aba4().setVisible(true);
                this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Esta Conta não é poupança!");
            new Aba4().setVisible(true);
                this.setVisible(false);
        }
        
        
    }//GEN-LAST:event_btConfirmarReajusteActionPerformed

    private void campoNovaTaxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNovaTaxaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNovaTaxaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(metodoReajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(metodoReajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(metodoReajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(metodoReajuste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new metodoReajuste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarReajuste;
    private javax.swing.JButton btConfirmarReajuste;
    private javax.swing.JTextField campoNCReajuste;
    private javax.swing.JTextField campoNovaTaxa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
