/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho1;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Paiva
 */
public class metodoDepositar extends javax.swing.JFrame {

    /**
     * Creates new form metodoDepositar
     */
    public metodoDepositar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancelarDepositar = new javax.swing.JButton();
        btConfirmarDepositar = new javax.swing.JButton();
        campoVSDepositar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoNCDepositar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 400));
        setSize(new java.awt.Dimension(450, 400));

        btCancelarDepositar.setText("Cancelar");
        btCancelarDepositar.setPreferredSize(new java.awt.Dimension(85, 25));
        btCancelarDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarDepositarActionPerformed(evt);
            }
        });

        btConfirmarDepositar.setText("Continuar");
        btConfirmarDepositar.setPreferredSize(new java.awt.Dimension(85, 25));
        btConfirmarDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarDepositarActionPerformed(evt);
            }
        });

        campoVSDepositar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoVSDepositar.setToolTipText("Ex: 100");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Valor do Deposito R$:");

        campoNCDepositar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNCDepositar.setToolTipText("Ex: 1010");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Nº da Conta:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("Depositar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoNCDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btConfirmarDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoVSDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(btCancelarDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNCDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoVSDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmarDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelarDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmarDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarDepositarActionPerformed
        int verificar = Integer.parseInt(campoNCDepositar.getText());
        
        if(verificar == Principal.conta1.getNumero()){
            int i = JOptionPane.showConfirmDialog(null, "Deseja confirmar o Depósito, senhor (a)"+Principal.conta1.getNome(),"Confirmação", JOptionPane.YES_NO_OPTION);
            if(i==0){
                if(Principal.conta1.depositar(Double.parseDouble(campoVSDepositar.getText()))==true){
                    JOptionPane.showMessageDialog(null, "Deposito efetuado com Sucesso!");
                    new Aba4().setVisible(true);
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Deposito não realizado!");
                    new Aba4().setVisible(true);
                    this.setVisible(false);}
            }else{
                
                new Aba4().setVisible(true);
                this.setVisible(false);
             }
        }
        
        else if(verificar == Principal.conta2.getNumero()){
            int i = JOptionPane.showConfirmDialog(null, "Deseja confirmar o Depósito, senhor (a)"+Principal.conta2.getNome(),"Confirmação", JOptionPane.YES_NO_OPTION);
            if(i==0){
                if(Principal.conta2.depositar(Double.parseDouble(campoVSDepositar.getText()))==true){
                    JOptionPane.showMessageDialog(null, "Deposito efetuado com Sucesso!");
                    new Aba4().setVisible(true);
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Deposito não realizado!");
                    new Aba4().setVisible(true);
                    this.setVisible(false);}
            }else{
                new Aba4().setVisible(true);
                this.setVisible(false);
             }
        }
        
        else if(verificar == Principal.conta3.getNumero()){
            int i = JOptionPane.showConfirmDialog(null, "Deseja confirmar o Depósito, senhor (a)"+Principal.conta3.getNome(),"Confirmação", JOptionPane.YES_NO_OPTION);
            if(i==0){
                if(Principal.conta3.depositar(Double.parseDouble(campoVSDepositar.getText()))==true){
                    JOptionPane.showMessageDialog(null, "Deposito efetuado com Sucesso!");
                    new Aba4().setVisible(true);
                     this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Deposito não realizado!");
                    new Aba4().setVisible(true);
                    this.setVisible(false);}
            }else{
                new Aba4().setVisible(true);
                this.setVisible(false);
             }
        }else{JOptionPane.showMessageDialog(null, "Conta Inexistente!");}
    }//GEN-LAST:event_btConfirmarDepositarActionPerformed

    private void btCancelarDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarDepositarActionPerformed
        new Aba4().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btCancelarDepositarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(metodoDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(metodoDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(metodoDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(metodoDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new metodoDepositar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarDepositar;
    private javax.swing.JButton btConfirmarDepositar;
    private javax.swing.JTextField campoNCDepositar;
    private javax.swing.JTextField campoVSDepositar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
