/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho1;

import javax.swing.JOptionPane;
    
/**
 *
 * @author Daniel Paiva
 */
public class metodoSacar extends javax.swing.JFrame {

     /**
     * Creates new form metodoSacar
     */
    public metodoSacar(){
        initComponents();
        
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNCSaque = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoVSSaque = new javax.swing.JTextField();
        btConfirmarSaque = new javax.swing.JButton();
        btCancelarSaque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 400));
        setSize(new java.awt.Dimension(450, 400));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Saque");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Nº da Conta:");

        campoNCSaque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNCSaque.setToolTipText("Ex: 321");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Valor do Saque R$:");

        campoVSSaque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoVSSaque.setToolTipText("Ex: 150.50");

        btConfirmarSaque.setText("Continuar");
        btConfirmarSaque.setPreferredSize(new java.awt.Dimension(85, 25));
        btConfirmarSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarSaqueActionPerformed(evt);
            }
        });

        btCancelarSaque.setText("Cancelar");
        btCancelarSaque.setMaximumSize(new java.awt.Dimension(83, 23));
        btCancelarSaque.setMinimumSize(new java.awt.Dimension(83, 23));
        btCancelarSaque.setPreferredSize(new java.awt.Dimension(85, 25));
        btCancelarSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarSaqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoNCSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btConfirmarSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoVSSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(btCancelarSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNCSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoVSSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmarSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelarSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btConfirmarSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarSaqueActionPerformed
        int verificar = Integer.parseInt(campoNCSaque.getText());
       
        if(verificar == Principal.conta1.getNumero()){
           
            int i = JOptionPane.showConfirmDialog(null, "Deseja confirmar o saque Senhor (a): "+Principal.conta1.getNome(),"Confirmação", JOptionPane.YES_NO_OPTION);
            
                if(i==0){ 
 
                        if(Principal.conta1.sacar(Double.parseDouble(campoVSSaque.getText()))==true){
                            JOptionPane.showMessageDialog(null, "Saque efetuado com Sucesso!");
                            new Aba4().setVisible(true);
                            this.setVisible(false);
                   
                    }else{
                            if(Double.parseDouble(campoVSSaque.getText())>0){
                                JOptionPane.showMessageDialog(null, "Saldo Insuficiente!");
                                new Aba4().setVisible(true);
                                this.setVisible(false);
                            }else{JOptionPane.showMessageDialog(null, "Valor digitado incompatível!");}
                     }
                }else{
                    new Aba4().setVisible(true);
                    this.setVisible(false);
                 }
                
        }
        
        else if(verificar == Principal.conta2.getNumero()){
            
            int i = JOptionPane.showConfirmDialog(null, "Deseja confirmar o saque Senhor (a): "+Principal.conta2.getNome(),"Confirmação", JOptionPane.YES_NO_OPTION);
            
                if(i==0){ 
 
                        if(Principal.conta2.sacar(Double.parseDouble(campoVSSaque.getText()))==true){
                            JOptionPane.showMessageDialog(null, "Saque efetuado com Sucesso!");
                            new Aba4().setVisible(true);
                            this.setVisible(false);
                   
                    }else{
                            if(Double.parseDouble(campoVSSaque.getText())>0){
                                JOptionPane.showMessageDialog(null, "Saldo Insuficiente!");
                                new Aba4().setVisible(true);
                                this.setVisible(false);
                            }else{JOptionPane.showMessageDialog(null, "Valor digitado incompatível!");}
                     }
                }else{
                    new Aba4().setVisible(true);
                    this.setVisible(false);
                 }
       
                }
        
        else if(verificar == Principal.conta3.getNumero()){
            int i = JOptionPane.showConfirmDialog(null, "Deseja confirmar o saque Senhor (a): "+Principal.conta3.getNome(),"Confirmação", JOptionPane.YES_NO_OPTION);

            if(i==0){ 
                    
                if(Principal.conta3.sacar(Double.parseDouble(campoVSSaque.getText()))==true){
                        JOptionPane.showMessageDialog(null, "Saque efetuado com Sucesso!");
                            new Aba4().setVisible(true);
                            this.setVisible(false);
                }else if((Principal.conta3.getSaldo() + ChequeEspecial.limite) >= Double.parseDouble(campoVSSaque.getText())){
                        
                        double ref = (Double.parseDouble((campoVSSaque.getText()))-(Principal.conta3.getSaldo()));
                        ChequeEspecial.limite -= ref;
                        Principal.conta3.depositar(ref);
                        Principal.conta3.sacar(Double.parseDouble(campoVSSaque.getText()));
                        JOptionPane.showMessageDialog(null, "Saque efetuado usando Cheque Especial!");
                        Principal.conta3.descontar(ref);
                            new Aba4().setVisible(true);
                            this.setVisible(false);                     
                    }else{
                        if(Double.parseDouble(campoVSSaque.getText())>0){
                                JOptionPane.showMessageDialog(null, "Saldo Insuficiente!");
                                new Aba4().setVisible(true);
                                this.setVisible(false);
                            }else{JOptionPane.showMessageDialog(null, "Valor digitado incompatível!");}
                      }
                }else{
                    new Aba4().setVisible(true);
                    this.setVisible(false);
                 }
         }else{JOptionPane.showMessageDialog(null, "Conta Inexistente!");}
        
    }//GEN-LAST:event_btConfirmarSaqueActionPerformed

    private void btCancelarSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarSaqueActionPerformed
        new Aba4().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btCancelarSaqueActionPerformed
    
    /**
     * @param args the command line arguments
     */
         
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(metodoSacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(metodoSacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(metodoSacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(metodoSacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new metodoSacar().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarSaque;
    private javax.swing.JButton btConfirmarSaque;
    private javax.swing.JTextField campoNCSaque;
    private javax.swing.JTextField campoVSSaque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
